register
surfriderfoundationeurope/labelcv-web pull request #132
Opened 2022-03-08 08:19 UTC by ZoRaFa

Salut salut ! Alors j'ai fini le formulaire (avec l'aide de @jeanremy  hein) et je vous montre le résultat.

![Register1](https://user-images.githubusercontent.com/78821052/157194875-7575b35c-2812-4e4b-9d13-db1c1d539e87.PNG)
![Register2](https://user-images.githubusercontent.com/78821052/157194902-4a32e376-f4f5-4081-b868-0bf6eb15b9ef.PNG)

2022-03-08 21:30 UTC, jeanremy requested changes
Cool , tu as bien avancé ! Tu as bien réutilisé les composants existants et utilisé le store 👍 
Je t'ai fait quelques retours sur la forme, mais la logique est là. 
Pour le conflit sur le devcontainer, à voir avec @cmaneu ce qu'il en pense, c'est lui le spécialiste !

2022-03-08 21:30 UTC, jeanremy commented on src/components/login/LoginForm.vue
> +                <a class="card__action" href="#/register">Create one here !</a>
Tu peux utiliser la balise `router-link`. ca permet de ne pas recharger la page, c'est le router qui prend en charge le chargement de la vue. Ca pourrait donner ça:
`<router-link to="/register" class="card__action">Create one here !</router-link>`

2022-03-08 21:30 UTC, jeanremy commented on src/components/register/RegisterForm.vue
> +.login {
```suggestion
.register {
```

2022-03-08 21:30 UTC, jeanremy commented on src/components/register/RegisterForm.vue
> +            status: "idle"
On peut utiliser des propriétés de model plus parlante, de ce type
```suggestion
            email: {
                error: false,
                value: ""
            },
            password: {
                error: false,
                value: ""
            },
            firstname: {
                error: false,
                value: ""
            },
            lastname: {
                error: false,
                value: ""
            },
            birthday: {
                error: false,
                value: ""
            },
            status: "idle"
```

2022-03-08 21:30 UTC, jeanremy commented on src/components/register/RegisterForm.vue
> +                type="number"
Un type number pour entrer une date de naissance n'est pas l'idéal. On pourrait utiliser le composant `<b-form-datepicker>`, qui met justement un champ date à disposition. Je ne sais pas ce qu'attend le back, mais on peut ensuite reformater la date comme on le souhaite avec ce type de champ, c'est bien pratique.
Sinon, on peut également utiliser le formattage du navigateur, qui aura un rendu à chaque fois différent en utilisant un input type=date

2022-03-08 21:30 UTC, jeanremy commented on src/components/register/RegisterForm.vue
> +                aria-describedby="first_name-constraints"
Cette propriété permet de lier un message d'erreur au champ, ce qui n'est pas le cas ici, ni sur les autres champs. On peut donc soit supprimer la propriété, soit ajouter un message d'erreur pour chaque champ (cette deuxième solution serait la mieux, tu as déjà toute la logique des erreurs dans ton model).

2022-03-08 21:30 UTC, jeanremy commented on src/components/register/RegisterForm.vue
> +                id="first_name"
```suggestion
                id="last_name"
```
Un petit oubli je pense, mais du coup le for et l'id ne correspondent pas.

2022-03-08 21:30 UTC, jeanremy commented on src/components/register/RegisterForm.vue
> +                type="name"
```suggestion
                type="text"
```

2022-03-08 21:30 UTC, jeanremy commented on src/components/register/RegisterForm.vue
> +                type="name"
```suggestion
                type="text"
```

2022-03-09 09:01 UTC, ZoRaFa commented
Merci @jeanremy ! j'ajouterais les modifs dans la semaine 👍

2022-03-14 18:46 UTC, jeanremy reviewed
Encore quelques petits retours, maison n'en est plus très loin à mon avis !

2022-03-14 18:46 UTC, jeanremy commented on src/components/register/RegisterForm.vue
> +                placeholder=" "
On peut le supprimer lui aussi
```suggestion
```

2022-03-14 18:46 UTC, jeanremy commented on src/components/register/RegisterForm.vue
> +                placeholder=" "
Même chose ici, si on ne l'utilise pas, autant le supprimer
```suggestion
```

2022-03-14 18:46 UTC, jeanremy commented on src/components/register/RegisterForm.vue
> +            <b-card-text>Register in. Please wait...</b-card-text>
Pas sûr que register in se dise :) 
```suggestion
            <b-card-text>Logged in. Please wait...</b-card-text>
```

2022-03-14 18:46 UTC, jeanremy commented on src/components/register/RegisterForm.vue
> +                type="password2"
```suggestion
                type="password"
```

2022-03-14 18:46 UTC, jeanremy commented on src/components/register/RegisterForm.vue
> +        }
Ici, il faudrait rajouter une condition pour vérifier que le mot de passe est identique à password2. On pourrat faire un gros switch pour gérer les différentes validations (la date de naissance, etc), mais ça peut être fait ensuite.

2022-03-14 18:46 UTC, jeanremy commented on src/components/register/RegisterForm.vue
> +            number: this.$data.number.value
```suggestion
            birthday: this.$data.birthday.value
```

2022-03-23 22:00 UTC, jeanremy reviewed
C'est cool ! J'ai juste rajouté un petit commentaire sur le switch. GitHub remonte aussi quelques errurs de formattage. As-tu prettier d'installé ?

2022-03-23 22:00 UTC, jeanremy commented on src/components/register/RegisterForm.vue
> +                id="password-constraints"
```suggestion
                id="confirm-password-constraints"
```
On ne peut pas avoir 2 ids dans une même page

2022-03-23 22:00 UTC, jeanremy commented on src/components/register/RegisterForm.vue
> +        }
```suggestion
        switch (input) {
            case "confirmpassword":
                if (
                    this.$data[input].value === "" ||
                    this.$data[input].value !== this.$data.password.value
                ) {
                    this.$data[input].error = true;
                }
                break;
             default:
                 if (this.$data[input].value === "") {
                     this.$data[input].error = true;
                 }
                 break;
        }
       
```

2022-03-24 07:37 UTC, ZoRaFa commented
Merci JR ! J'ai ajouté les modifs et j'ai aussi installé Prettier

2022-03-29 19:12 UTC, jeanremy reviewed
Juste un petit oubli, sinon, ça me semble bien !

2022-03-29 19:12 UTC, jeanremy commented on src/store/store.ts
> +            console.log("register ~ credentials", credentials);
```suggestion
```
Petit oubli de console.log :)

2022-03-29 19:52 UTC, ZoRaFa commented on src/store/store.ts
> +            console.log("register ~ credentials", credentials);
Merci :)

2022-03-30 20:13 UTC, jeanremy commented
Je me suis permis de pousser quelques modifs lors de mes tests. J'ai harmonisé les noms de champs dans le model avec les ids. J'ai rajouté les messages d'erreur sur tous les champs, remplacé l'input checbox par un composant de bootstrap vue. J'ai fixé l'envoi de données et les checks. De mon côté, c'est bon.

2022-04-27 20:15 UTC, jeanremy approved these changes

2022-05-03 11:10 UTC, merged