Feature/login
surfriderfoundationeurope/labelcv-web pull request #91
Opened 2021-05-16 20:19 UTC by jeanremy

Adds a login page and some links in the navbar: login, upload (not ready yet) and logout. 

https://www.loom.com/share/6dff018fb1a24c1fa17fc4b63e7a0661

2021-05-19 15:15 UTC, bertrandlalo requested changes
Top !! Juste une petite suggestion : déplacer la requête Axios dans les actions du store.

2021-05-19 15:15 UTC, bertrandlalo commented on src/components/login/LoginForm.vue
> +            });
Je mettrais ça plutôt comme une action du store Vuex. T'en penses quoi ?  
Pas besoin du getter`getAxiosRequestConfig` du coup. 
[Eventuellement, possibilité en dev de skipper Axios quand useAxios = False]

2021-05-19 19:29 UTC, jeanremy commented on src/components/login/LoginForm.vue
> +            });
Carrément, j'y avais pensé, mais je comptais tout mettre dedans et j'étais un peu embêté pour gérer le statut. J'ai trouvé un entre-deux: l'appel api est géré dans une action, et son retour dans le composant. Qu'en penses-tu ?

2021-06-11 20:44 UTC, jeanremy commented
Hello ! J'ai fixé le login, en fait, on était redirigé en cas d'erreur. C'est bon, j'ai fait une petite démo également:

https://www.loom.com/share/04f97b2b594c4e58b0fa9680faa65def

2021-07-23 11:43 UTC, bertrandlalo commented on src/components/login/LoginForm.vue
> +            });
ok, ça me va !

2021-07-23 11:45 UTC, merged